#!/usr/bin/env node
/**
 * Bulk-creates Wiki.js local accounts from a CSV of MIC members, so that
 * self-registration can stay OFF and only pre-approved members ever get in.
 *
 * Usage:
 *   WIKI_URL=https://wiki.example.com \
 *   WIKI_ADMIN_TOKEN=eyJhbGciOi... \
 *   node provision-members.js members.csv
 *
 * members.csv format (header row required):
 *   name,email
 *   Jane Doe,jane.doe@vitstudent.ac.in
 *
 * WIKI_ADMIN_TOKEN: an API access token generated by an admin account under
 * Administration > API Access in the Wiki.js UI (Admin > Utilities > API tab).
 *
 * NOTE: verify the `users.create` mutation shape below against your actual
 * Wiki.js version's GraphQL schema before a real run (Administration >
 * Utilities > GraphQL Playground lets you introspect it) — field names have
 * shifted across Wiki.js 2.x releases. Run with --dry-run first regardless.
 */

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const WIKI_URL = process.env.WIKI_URL;
const WIKI_ADMIN_TOKEN = process.env.WIKI_ADMIN_TOKEN;
const csvPath = process.argv[2];
const dryRun = process.argv.includes("--dry-run");

if (!csvPath) {
  console.error("Usage: node provision-members.js <members.csv> [--dry-run]");
  process.exit(1);
}
if (!dryRun && (!WIKI_URL || !WIKI_ADMIN_TOKEN)) {
  console.error("Set WIKI_URL and WIKI_ADMIN_TOKEN env vars (or pass --dry-run to preview without calling the API).");
  process.exit(1);
}

function parseCsv(text) {
  const lines = text.trim().split(/\r?\n/);
  const header = lines.shift().split(",").map((h) => h.trim().toLowerCase());
  const nameIdx = header.indexOf("name");
  const emailIdx = header.indexOf("email");
  if (nameIdx === -1 || emailIdx === -1) {
    throw new Error('CSV must have "name" and "email" columns');
  }
  return lines
    .filter((l) => l.trim().length > 0)
    .map((line) => {
      const cols = line.split(",");
      return { name: cols[nameIdx].trim(), email: cols[emailIdx].trim().toLowerCase() };
    });
}

function randomPassword() {
  return crypto.randomBytes(9).toString("base64url");
}

const CREATE_USER_MUTATION = `
  mutation ($email: String!, $name: String!, $passwordRaw: String!) {
    users {
      create(
        email: $email
        name: $name
        passwordRaw: $passwordRaw
        providerKey: "local"
        groups: [2]
        mustChangePassword: true
        sendWelcomeEmail: false
      ) {
        responseResult {
          succeeded
          errorCode
          message
        }
        user {
          id
        }
      }
    }
  }
`;

async function createUser(member, tempPassword) {
  const res = await fetch(`${WIKI_URL.replace(/\/$/, "")}/graphql`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${WIKI_ADMIN_TOKEN}`,
    },
    body: JSON.stringify({
      query: CREATE_USER_MUTATION,
      variables: { email: member.email, name: member.name, passwordRaw: tempPassword },
    }),
  });
  const json = await res.json();
  if (json.errors) {
    return { succeeded: false, message: json.errors.map((e) => e.message).join("; ") };
  }
  return json.data.users.create.responseResult;
}

async function main() {
  const members = parseCsv(fs.readFileSync(csvPath, "utf8"));
  console.log(`Loaded ${members.length} member(s) from ${csvPath}`);

  const results = [];
  for (const member of members) {
    const tempPassword = randomPassword();

    if (dryRun) {
      console.log(`[dry-run] would create ${member.name} <${member.email}>`);
      results.push({ ...member, tempPassword, status: "dry-run" });
      continue;
    }

    try {
      const result = await createUser(member, tempPassword);
      if (result.succeeded) {
        console.log(`✓ created ${member.email}`);
        results.push({ ...member, tempPassword, status: "created" });
      } else {
        console.error(`✗ ${member.email}: ${result.message}`);
        results.push({ ...member, tempPassword: "", status: `failed: ${result.message}` });
      }
    } catch (err) {
      console.error(`✗ ${member.email}: ${err.message}`);
      results.push({ ...member, tempPassword: "", status: `failed: ${err.message}` });
    }
  }

  const outPath = path.join(path.dirname(csvPath), "members-provisioned.csv");
  const outCsv = ["name,email,temp_password,status"]
    .concat(results.map((r) => `${r.name},${r.email},${r.tempPassword},${r.status}`))
    .join("\n");
  fs.writeFileSync(outPath, outCsv);

  console.log(`\nWrote temp passwords + status to ${outPath}`);
  console.log("Share each temp password with its member over a private channel (not email/Slack in plaintext) — they must change it on first login.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
